"""Core classes and logic for NCLint."""

from abc import ABCMeta, abstractmethod
from dataclasses import dataclass
from enum import Enum
from importlib import import_module
from pkgutil import walk_packages
from types import ModuleType
from typing import ClassVar, Protocol, runtime_checkable
from ciscoconfparse2 import CiscoConfParse  # type: ignore[import-untyped]


class Severity(Enum):
    """Severity levels for findings."""

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"
    HINT = "hint"


@dataclass
class Finding:
    """Represents a single finding from a rule analysis.

    Attributes:
        rule_id: The ID of the rule that generated this finding
        severity: The severity level of the finding
        message: A descriptive message about the finding
        line: The line number in the configuration where the issue was found
    """

    rule_id: str
    severity: Severity
    message: str
    line: int = 0


class BaseNCLintRule(metaclass=ABCMeta):
    """Base class for all NCLint rules.

    Attributes:
        parse: The CiscoConfParse object representing the configuration to analyze
        id: Unique identifier for the rule
        severity: Severity level of findings generated by this rule
        description: A brief description of what the rule checks for
    """

    id: ClassVar[str]
    severity: ClassVar[Severity]
    description: ClassVar[str]

    def __init__(self, parse: CiscoConfParse):  # type: ignore[no-any-unimported]
        self.parse = parse

    def __init_subclass__(cls, **kwargs: object) -> None:
        """Ensure that severity is a valid value."""
        super().__init_subclass__(**kwargs)
        if not isinstance(cls.severity, Severity):
            raise AttributeError(
                f"Severity Enum class must be used, got {cls.severity!r}"
            )

    @abstractmethod
    def valid_os(self) -> bool:
        """Check if the rule is applicable to the current configuration's OS."""

    @abstractmethod
    def analyze(self) -> list[Finding]:
        """Analyze the configuration and return a list of findings."""


@runtime_checkable
class BaseNCLintRuleClass(Protocol):  # pylint: disable=too-few-public-methods
    """Protocol describing the class-level interface of an BaseNCLintRule subclass.

    Attributes:
        parse: The CiscoConfParse object representing the configuration to analyze
        id: Unique identifier for the rule
        severity: Severity level of findings generated by this rule
        description: A brief description of what the rule checks for
    """

    id: str
    severity: Severity
    description: str

    def __call__(  # type: ignore[no-any-unimported]
        self, parse: CiscoConfParse
    ) -> BaseNCLintRule: ...


class AnalyzerEngine:  # pylint: disable=too-few-public-methods
    """Engine to run all registered rules against a given configuration.

    Attributes:
        parse: The CiscoConfParse object representing the configuration to analyze
        rules: A list of rule classes to execute
    """

    def __init__(  # type: ignore[no-any-unimported]
        self, parse: CiscoConfParse, rules: list[BaseNCLintRuleClass]
    ):
        self.parse = parse
        self.rules = rules

    def run(self) -> list[Finding]:
        """Run all rules and collect findings."""
        findings: list[Finding] = []
        for rule_cls in self.rules:
            rule = rule_cls(self.parse)
            if not rule.valid_os():
                continue

            try:
                results = rule.analyze()

                if results:
                    findings.extend(results)

            except Exception as e:  # pylint: disable=broad-exception-caught
                findings.append(Finding(rule_cls.id, Severity.ERROR, str(e)))

        return sorted(findings, key=lambda f: f.line)


class RuleRegistry:  # pylint: disable=too-few-public-methods
    """Registry to discover and store all available rules.

    Attributes:
        package: The package to search for rule modules
        rules: A list of discovered rule classes
    """

    def __init__(self, package: ModuleType):
        self.rules: list[BaseNCLintRuleClass] = []
        self._discover(package)

    def _discover(self, package: ModuleType) -> None:
        """Discover and import all rule modules in the given package."""
        for _, modname, _ in walk_packages(package.__path__, package.__name__ + "."):
            try:
                module = import_module(modname)
                for attr in dir(module):
                    obj = getattr(module, attr)
                    if isinstance(obj, BaseNCLintRuleClass):
                        self.rules.append(obj)
                    elif isinstance(obj, ABCMeta) and obj.__name__ != "BaseNCLintRule":
                        raise ModuleNotFoundError(
                            f"{obj.__name__} does not conform to BaseNCLintRuleClass protocol."
                        )
            except (AttributeError, ModuleNotFoundError) as e:
                print(f"Error importing {modname}: {e}")
